export default {
    CUSTOM_LINK_INNER_STROKE_WIDTH: 4,
    CUSTOM_LINK_OUTER_STROKE_COLOR: '#c8c8c8',
    CUSTOM_LINK_OUTER_STROKE_WIDTH: 20,
    CUSTOM_LINK_LINE_DASH: [4, 4],

    STANDARD_LINK_INNER_STROKE_COLOR: '#ccc',
    STANDARD_LINK_INNER_STROKE_WIDTH: 4,
    STANDARD_LINK_OUTER_STROKE_COLOR: 'rgba(200,200,200,0.01)',
    STANDARD_LINK_OUTER_STROKE_WIDTH: 20,
    STANDARD_LINK_LINE_DASH: [1, 0],

    GROUP_TITLE_COLOR: '#666',

    NODE_HIGHLIGHT_COLOR: 'yellow',
    NODE_SHAPE_FILL_COLOR: '#fff',

    NODE_LEAD_FILL: '#e67447',
    NODE_LEAD_STROKE: '#e98e6a',
    NODE_LEAD_SELECTED_FILL: '#e98e6a',
    NODE_LEAD_SELECTED_STROKE: '#e67447',

    NODE_USER_FILL: 'rgb(48,127,211)',
    NODE_USER_STROKE: 'rgb(48,127,211)',
    NODE_USER_SELECTED_FILL: 'rgb(64, 160, 255)',
    NODE_USER_SELECTED_STROKE: 'rgb(48,127,211)',

    NODE_NAME_FONT: 'bold 20pt sans-serif',
    NODE_NAME_COLOR: '#222',
    NODE_TITLE_FONT: '12pt sans-serif',
    NODE_TITLE_COLOR: '#666',

    NODE_EXTENDED_FIELDS_FONT: '7pt sans-serif',
    NODE_EXTENDED_FIELDS_COLOR: '#666',

    NON_KEYSTAKEHOLDER_NAME_FONT: '20pt sans-serif',
    NON_KEYSTAKEHOLDER_NAME_COLOR: '#787878',
    NON_KEYSTAKEHOLDER_SHAPE_COLOR: '#ededed',

    NODE_STROKE_COLOR: '#afafaf',
    NODE_HEAD_COLOR: '#afafaf',
    NODE_SELECTED_STROKE_COLOR: 'rgb(155, 219, 255)',
    NODE_SELECTED_FILL_COLOR: 'rgba(63, 245, 63, 0.5)',
    NODE_SELECTED_FILL: 'rgb(159, 250, 159)',

    NODE_SELECTED_UNDERLAY_COLOR: 'rgba(155, 219, 255, 0.6)',
    NODE_SELECTED_OVERLAY_COLOR: 'rgba(155, 219, 255, 0.2)',
    NODE_SELECTED_BOUNDARY_SIZE: 10,

    NODE_STROKE_WIDTH: 2,
    NODE_CORNER_RADIUS: 20,
    NODE_HEAD_PANEL_MIN_WIDTH: 90,
    NODE_HEAD_PANEL_MIN_HEIGHT: 110,
    NODE_CONTENT_PANEL_WIDTH: 100,
    NODE_HEAD_ICON_CROP_RADIUS: 70,
    NODE_HEAD_ICON_WIDTH: 70,
    NODE_HEAD_ICON_HEIGHT: 70,

    NODE_DETAIL_BUTTON_FONT: '8pt sans-serif',
    NODE_DETAIL_BUTTON_FONT_COLOR: '#eee',
    NODE_DETAIL_BUTTON_COLOR: '#3d6181',
    NODE_DETAIL_BUTTON_HIGHLIGHT_COLOR: '#ea1776',
    NODE_DETAIL_BUTTON_WIDTH: 22,
    NODE_DETAIL_BUTTON_HEIGHT: 22,

    NODE_LEFT_PADDING: 10,
    NODE_RIGHT_PADDING: 10,

    // --------------------------------------------------

    NODE_INFLUENCE_DEFAULT_IMAGE_HEIGHT: 30,
    NODE_INFLUENCE_DEFAULT_BUTTON_COLOR: '#999',
    NODE_INFLUENCE_DEFAULT_BUTTON_WIDTH: 20,
    NODE_INFLUENCE_DEFAULT_BUTTON_HEIGHT: 20,

    NODE_INFLUENCE_LOW_BUTTON_COLOR: '#b6b6b6',
    NODE_INFLUENCE_LOW_BUTTON_WIDTH: 20,
    NODE_INFLUENCE_LOW_BUTTON_HEIGHT: 20,
    NODE_INFLUENCE_LOW_SHAPE_ANGLE: 180,

    NODE_INFLUENCE_MEDIUM_BUTTON_COLOR: '#deb200',
    NODE_INFLUENCE_MEDIUM_BUTTON_WIDTH: 20,
    NODE_INFLUENCE_MEDIUM_SHAPE_ANGLE: 45,

    NODE_INFLUENCE_HIGH_BUTTON_COLOR: '#39b54a',
    NODE_INFLUENCE_HIGH_BUTTON_WIDTH: 20,
    NODE_INFLUENCE_HIGH_SHAPE_ANGLE: 0,

    // --------------------------------------------------

    NODE_SUPPORT_DEFAULT_IMAGE_HEIGHT: 30,
    NODE_SUPPORT_DEFAULT_BUTTON_COLOR: '#999',
    NODE_SUPPORT_DEFAULT_BUTTON_FONT: 'bold 20pt sans-serif',
    NODE_SUPPORT_DEFAULT_BUTTON_FONT_COLOR: '#fff',
    NODE_SUPPORT_DEFAULT_BUTTON_WIDTH: 75,
    NODE_SUPPORT_DEFAULT_BUTTON_HEIGHT: 24,

    NODE_SUPPORT_BLOCKER_BUTTON_COLOR: '#ea1a37',
    NODE_SUPPORT_BLOCKER_BUTTON_FONT: 'bold 7pt sans-serif',
    NODE_SUPPORT_BLOCKER_BUTTON_FONT_COLOR: '#fff',
    NODE_SUPPORT_BLOCKER_BUTTON_WIDTH: 75,
    NODE_SUPPORT_BLOCKER_BUTTON_HEIGHT: 24,

    NODE_SUPPORT_FLOATER_BUTTON_COLOR: '#afafaf',
    NODE_SUPPORT_FLOATER_BUTTON_FONT: 'bold 7pt sans-serif',
    NODE_SUPPORT_FLOATER_BUTTON_FONT_COLOR: '#fff',
    NODE_SUPPORT_FLOATER_BUTTON_WIDTH: 75,
    NODE_SUPPORT_FLOATER_BUTTON_HEIGHT: 24,

    NODE_SUPPORT_SUPPORTER_BUTTON_COLOR: '#00b09a',
    NODE_SUPPORT_SUPPORTER_BUTTON_FONT: 'bold 7pt sans-serif',
    NODE_SUPPORT_SUPPORTER_BUTTON_FONT_COLOR: '#fff',
    NODE_SUPPORT_SUPPORTER_BUTTON_WIDTH: 75,
    NODE_SUPPORT_SUPPORTER_BUTTON_HEIGHT: 24,

    NODE_SUPPORT_CHAMPION_BUTTON_COLOR: '#39b54a',
    NODE_SUPPORT_CHAMPION_BUTTON_FONT: 'bold 7pt sans-serif',
    NODE_SUPPORT_CHAMPION_BUTTON_FONT_COLOR: '#fff',
    NODE_SUPPORT_CHAMPION_BUTTON_WIDTH: 75,
    NODE_SUPPORT_CHAMPION_BUTTON_HEIGHT: 24,

    // --------------------------------------------------
    REL_LINE_BACKGROUND_COLOR: '#f5f5f5',

    DRAW_REL_ICON_BACKGROUND: 'fill: none;stroke-miterlimit: 10;stroke: {color};stroke-width: 25px;opacity: 1.0;',
    DRAW_REL_ICON_ARROW: 'fill: {color};',
    DRAW_REL_ICON_DASH: 'fill: none;stroke-miterlimit: 10;stroke: {color};stroke-width: 8px;stroke-dasharray: 8;'
};